name: Python Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python setup.py install && pip install pytest coverage
    - name: Test with unittest
      run: |
        coverage run --source="./Tea" -m pytest tests/test_*
    - name: CodeCov
      run: bash <(curl -s https://codecov.io/bash) -cF python
